AllCops:
  DisplayCopNames: true
  Exclude:
    - config/initializers/secret_token.rb

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 1500

Style/Documentation:
  Enabled: false
