development:
  adapter: postgresql
  encoding: unicode
  database: usagle_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5  } %>
  username: postgres
  password: kDCw9PD3tdEB0U1w5mQi

test:
  adapter: postgresql
  encoding: unicode
  database: usagle_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5   } %>
  username: postgres
  password: kDCw9PD3tdEB0U1w5mQi

production:
  adapter: postgresql
  encoding: unicode
  database: usagle_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5    } %>
  username: postgres
  password: kDCw9PD3tdEB0U1w5mQi
